version: "3.7"
services:
  v2ray:
    image: v2fly/v2fly-core
    restart: unless-stopped
    container_name: v2fly-core
    volumes:
      - ./config.json:/etc/v2ray/config.json
    ports:
      - 1081:1081
    dns:
      - 8.8.8.8
      - 8.8.4.4